language: ruby
cache: bundler
sudo: false
services:
  - redis-server
rvm:
  - 2.6
  - 2.5
  - 2.4
  - 2.3
  - 2.2
  - 2.1
  - 2.0
env:
  - USE_REAL_REDIS=true
gemfile:
  - gemfiles/redis_3.gemfile
  - gemfiles/redis_4.gemfile
script:
  - bundle exec rspec
before_install:
  - gem install rubygems-update -v 3.4.22
